# Generated by Django 3.1.5 on 2021-01-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20210130_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='reduced_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
