# Generated by Django 3.1.5 on 2021-01-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210130_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='reduced_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
