# Generated by Django 3.1.5 on 2021-01-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20210131_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Bensin', 'Bensin'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('EL', 'EL'), ('Ethanol', 'Ethanol')], max_length=10),
        ),
    ]
